# Main plugin definition
name: PrivateChest
version: 2.1
main: me.tuplugin.privatechest.PrivateChest
# Minimum Spigot/Paper API version required (1.16 ensures modern methods)
api-version: 1.16
author: Koyere
description: A plugin that allows players to lock chests with a personal password.
# Optional: Link to your SpigotMC or GitHub page
website: https://www.spigotmc.org/resources/privatechest.124359/

# Command definitions
commands:
  lockchest:
    description: Lock the container you're looking at using a password.
    usage: /lockchest <password>

  unlockchest:
    description: Unlock your locked container by entering the password.
    usage: /unlockchest <password>

  privatechest:
    description: Reload PrivateChest configuration and messages.
    usage: /privatechest reload
    # Optional: Added a short alias for convenience
    aliases: [pc]

  clearchests:
    description: Remove orphaned container entries from data.yml.
    usage: /clearchests

  trust:
    description: Give another player access to your locked containers.
    usage: /trust <player> or /trust list

  untrust:
    description: Remove access from a player to your locked containers.
    usage: /untrust <player> or /untrust all

  renamecontainer:
    description: Set or remove a custom name for a protected container.
    usage: /renamecontainer <name> or /renamecontainer remove
    aliases: [renamechest]

# Permission definitions
permissions:
  privatechest.use:
    description: Allows players to use /lockchest, /unlockchest, /trust, /untrust, and /renamecontainer.
    # Defaults to true, so all players can use it unless a permission plugin overrides it.
    default: true

  privatechest.admin:
    description: Allows use of admin commands and bypass protection.
    # Defaults to op, so only server operators have admin rights by default.
    default: op

  # Chest limit permissions
  privatechest.limit.unlimited:
    description: Allows unlimited chest locks.
    default: false

  privatechest.limit.1000:
    description: Allows locking up to 1000 chests.
    default: false

  privatechest.limit.500:
    description: Allows locking up to 500 chests.
    default: false

  privatechest.limit.100:
    description: Allows locking up to 100 chests.
    default: false

  privatechest.limit.50:
    description: Allows locking up to 50 chests.
    default: false

  privatechest.limit.25:
    description: Allows locking up to 25 chests.
    default: false

  privatechest.limit.20:
    description: Allows locking up to 20 chests.
    default: false

  privatechest.limit.15:
    description: Allows locking up to 15 chests.
    default: false

  privatechest.limit.10:
    description: Allows locking up to 10 chests.
    default: false

  privatechest.limit.5:
    description: Allows locking up to 5 chests.
    default: false

  privatechest.limit.3:
    description: Allows locking up to 3 chests.
    default: false

  privatechest.limit.1:
    description: Allows locking up to 1 chest.
    default: false

  # Granular container type limits (examples - more can be added as needed)
  # Format: privatechest.limit.{container_type}.{number}
  
  # Chest limits
  privatechest.limit.chest.unlimited:
    description: Allows unlimited chest locks.
    default: false
  privatechest.limit.chest.50:
    description: Allows locking up to 50 chests.
    default: false
  privatechest.limit.chest.25:
    description: Allows locking up to 25 chests.
    default: false
  privatechest.limit.chest.10:
    description: Allows locking up to 10 chests.
    default: false

  # Barrel limits
  privatechest.limit.barrel.unlimited:
    description: Allows unlimited barrel locks.
    default: false
  privatechest.limit.barrel.20:
    description: Allows locking up to 20 barrels.
    default: false
  privatechest.limit.barrel.10:
    description: Allows locking up to 10 barrels.
    default: false
  privatechest.limit.barrel.5:
    description: Allows locking up to 5 barrels.
    default: false

  # Shulker box limits
  privatechest.limit.shulker_box.unlimited:
    description: Allows unlimited shulker box locks.
    default: false
  privatechest.limit.shulker_box.10:
    description: Allows locking up to 10 shulker boxes.
    default: false
  privatechest.limit.shulker_box.5:
    description: Allows locking up to 5 shulker boxes.
    default: false
  privatechest.limit.shulker_box.3:
    description: Allows locking up to 3 shulker boxes.
    default: false
  privatechest.limit.shulker_box.1:
    description: Allows locking up to 1 shulker box.
    default: false