name: PrivateChest
version: 1.6.2
main: me.tuplugin.privatechest.PrivateChest
api-version: 1.16
author: Koyere
description: A plugin that allows players to lock chests with a personal password.

commands:
  lockchest:
    description: Lock the chest you're looking at using a password.
    usage: /lockchest <password>

  unlockchest:
    description: Unlock your locked chest by entering the password.
    usage: /unlockchest <password>

  privatechest:
    description: Reload PrivateChest configuration and messages.
    usage: /privatechest reload

  clearchests:
    description: Remove orphaned chest entries from data.yml.
    usage: /clearchests

permissions:
  privatechest.use:
    description: Allows players to use /lockchest and /unlockchest.
    default: true

  privatechest.admin:
    description: Allows use of admin commands like /privatechest reload and /clearchests.
    default: op
